/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.intvaria.form;

import com.intvaria.DAO.UserDAO;
import com.intvaria.entity.User;
import com.intvaria.main.EditUser;
import com.intvaria.main.Main;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dhanushka
 */
public class AllUsers extends javax.swing.JPanel {

    UserDAO userDao=new UserDAO();

    public AllUsers() {
        initComponents();
     //   jTable1.setRowHeight(1, 30);
     jTable1.getTableHeader().setOpaque(true);
     jTable1.getTableHeader().setBackground(Color.RED);
      
        getAllUsers();
    }

    
    public void getAllUsers(){
        ArrayList<User> userList=(ArrayList<User>) userDao.getAllUsers();
        String username,fullname,nic,mobile,userType;
        if(userList.size()>0){
            for(int i=0;i < userList.size();i++){
                username=userList.get(i).getUserName();
                fullname=userList.get(i).getFirstName()+" "+userList.get(i).getLastName();
                nic=userList.get(i).getNic();
                mobile=userList.get(i).getMobile();
                userType=userList.get(i).getUserType();
                String toData[]={username,userType,fullname,nic,mobile};
                DefaultTableModel tbMdel=(DefaultTableModel) jTable1.getModel();
                tbMdel.addRow(toData);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        roundPanel1 = new com.intvaria.swing.RoundPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        combType = new javax.swing.JComboBox<String>();
        txtKeyword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jPopupMenu1.setPreferredSize(new java.awt.Dimension(150, 50));
        jPopupMenu1.setRequestFocusEnabled(false);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setText("Edit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2.setText("Delete");
        jMenuItem2.setPreferredSize(new java.awt.Dimension(69, 22));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setBackground(new java.awt.Color(51, 51, 51));

        roundPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "User type", "Full  Name", "NIC", "Mobile"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        combType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combType.setForeground(new java.awt.Color(255, 255, 255));
        combType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Username", "NIC Number" }));
        combType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combTypeItemStateChanged(evt);
            }
        });
        combType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combTypeActionPerformed(evt);
            }
        });
        combType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combTypeKeyPressed(evt);
            }
        });

        txtKeyword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtKeyword.setEnabled(false);
        txtKeyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeywordKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(combType, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       searchUser();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void searchUser(){
         DefaultTableModel dm = (DefaultTableModel)jTable1.getModel();
     dm.getDataVector().removeAllElements();
       dm.fireTableDataChanged();
        int type=combType.getSelectedIndex();
        String keyWord=txtKeyword.getText();
         List<User> userList;
        if(type==0){
            userList=userDao.getAllUsers();
        }else{
            userList=userDao.searchUser(type, keyWord);
        }
            
         
        
        String username,fullname,nic,mobile,userType;
        if(userList.size()>0){
            for(int i=0;i < userList.size();i++){
                username=userList.get(i).getUserName();
                fullname=userList.get(i).getFirstName()+" "+userList.get(i).getLastName();
                nic=userList.get(i).getNic();
                mobile=userList.get(i).getMobile();
                userType=userList.get(i).getUserType();
                String toData[]={username,userType,fullname,nic,mobile};
                DefaultTableModel tbMdel=(DefaultTableModel) jTable1.getModel();
                tbMdel.addRow(toData);
            }
        }
        
    }
    
    private void combTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combTypeItemStateChanged
      
        if(combType.getSelectedIndex()!=0){
            txtKeyword.setEnabled(true);
        }else{
            txtKeyword.setEnabled(false);
        }
        
    }//GEN-LAST:event_combTypeItemStateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      //  JOptionPane.showMessageDialog(null, "dd");
      
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
      if(evt.isPopupTrigger()){
          JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            
             if (! source.isRowSelected(row))
                source.changeSelection(row, column, false, false);
            
         jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
      }
    }//GEN-LAST:event_jTable1MouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     
        Frame[] farame1 = Main.getFrames();

        int index = jTable1.getSelectedRow();
        TableModel tbm = jTable1.getModel();
        String username = (String) tbm.getValueAt(index, 0);
        User user = userDao.getLoggedUserDetails();

        if (user.getUserType().equals("admin")) {
            for (int i = 0; i < farame1.length; i++) {
                farame1[i].setExtendedState(JFrame.ICONIFIED);// One way
            }
            JFrame edit = new EditUser(username);
            edit.setVisible(true);
        } else {
            if (user.getUserName().equals(username)) {
                for (int i = 0; i < farame1.length; i++) {
                    farame1[i].setExtendedState(JFrame.ICONIFIED);// One way
                }
                JFrame edit = new EditUser(username);
                edit.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "You are not a admin. So you can't edit other user details ! ");
            }

        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
     int option=   JOptionPane.showConfirmDialog(null, "Do you want to delete this user?");
        if(option == JOptionPane.YES_OPTION){
             User loggedUser= userDao.getLoggedUserDetails();
            
            if(loggedUser.getUserType().equals("admin")){
                  int index=   jTable1.getSelectedRow();
             TableModel tbm=jTable1.getModel();
             String username=(String) tbm.getValueAt(index, 0);
          boolean isDeleted=userDao.deleteUser(username);
          
          if(isDeleted==true){
              JOptionPane.showMessageDialog(null, "User deleted ");
                DefaultTableModel dm = (DefaultTableModel)jTable1.getModel();
     dm.getDataVector().removeAllElements();
       dm.fireTableDataChanged();
              getAllUsers();
              
          }else{
              JOptionPane.showMessageDialog(null, "User can't deleted. Try agin! ");
          }
            }else{
                 JOptionPane.showMessageDialog(null, "You are not a admin. So you can't delete users ! ");
            }
         
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtKeywordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeywordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchUser();
        
        }
    }//GEN-LAST:event_txtKeywordKeyPressed

    private void combTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combTypeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchUser();
        
        }
    }//GEN-LAST:event_combTypeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combType;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.intvaria.swing.RoundPanel roundPanel1;
    private javax.swing.JTextField txtKeyword;
    // End of variables declaration//GEN-END:variables
}
