/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.intvaria.form;

import com.intvaria.DAO.MemberDAO;
import com.intvaria.DAO.PackageDAO;
import com.intvaria.entity.Member;
import com.intvaria.entity.Options;
import com.intvaria.entity.PackageDetails;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicScrollBarUI;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Dhanushka
 */
public class Register extends javax.swing.JPanel {

   
    byte[] image;
    String imagePath="";
    ImageIcon myImage;
    PackageDAO pacDao=new PackageDAO();
    MemberDAO memberDao=new MemberDAO();
    File f;
    public Register() {
        initComponents();
        setPackages();
      
       jScrollPane2.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
    @Override
    protected void configureScrollBarColors() {
        this.thumbColor =new Color(0,153,153);
    }
});
       
       
       opt1Y.setActionCommand("Yes");
       opt1N.setActionCommand("No");
       
        opt2Y.setActionCommand("Yes");
       opt2N.setActionCommand("No");
       
        opt3Y.setActionCommand("Yes");
       opt3N.setActionCommand("No");
       
        opt4Y.setActionCommand("Yes");
       opt4N.setActionCommand("No");
       
        opt5Y.setActionCommand("Yes");
       opt5N.setActionCommand("No");
       
        opt6Y.setActionCommand("Yes");
       opt6N.setActionCommand("No");
       
        opt7Y.setActionCommand("Yes");
       opt7N.setActionCommand("No");
       
        opt8Y.setActionCommand("Yes");
       opt8N.setActionCommand("No");
       
        opt9Y.setActionCommand("Yes");
       opt9N.setActionCommand("No");
       
        opt10Y.setActionCommand("Yes");
       opt10N.setActionCommand("No");
       
        opt11Y.setActionCommand("Yes");
       opt11N.setActionCommand("No");
    }
    
    
      
    private void setPackages(){
        Vector comboBoxItems=new Vector();
        List<PackageDetails> packList=pacDao.getAllPackages();
        
        if(packList.size()>0){
            for(int i=0 ; i< packList.size() ; i++){
                comboBoxItems.add(packList.get(i).getName());
            }
             final DefaultComboBoxModel model = new DefaultComboBoxModel(comboBoxItems);
             jComboBox3.setModel(model);
        }
    }
    
    public ImageIcon setIcon(String m,byte[] image){
        if(m!=null){
            myImage=new ImageIcon(m);
            
        }else{
            myImage=new ImageIcon(image);
        }
        
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(proImage.getWidth(), proImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon  i=new ImageIcon(img2);
        return i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel6 = new com.intvaria.swing.RoundPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        roundPanel1 = new com.intvaria.swing.RoundPanel();
        header2 = new com.intvaria.component.Header();
        jLabel1 = new javax.swing.JLabel();
        proImage = new com.intvaria.swing.ImageAvatar();
        imageName = new javax.swing.JLabel();
        imagePath2 = new javax.swing.JLabel();
        JFileChooser = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        roundPanel21 = new com.intvaria.swing.RoundPanel();
        txtMembershipNum = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jLabel19 = new javax.swing.JLabel();
        roundPanel5 = new com.intvaria.swing.RoundPanel();
        txtBirthDay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        roundPanel19 = new com.intvaria.swing.RoundPanel();
        txtLastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        roundPanel4 = new com.intvaria.swing.RoundPanel();
        txtFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        roundPanel7 = new com.intvaria.swing.RoundPanel();
        txtMobile = new javax.swing.JTextField();
        roundPanel11 = new com.intvaria.swing.RoundPanel();
        txtNic = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        roundPanel12 = new com.intvaria.swing.RoundPanel();
        txtHomeAddress = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        roundPanel13 = new com.intvaria.swing.RoundPanel();
        txtOfficeAddress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        roundPanel8 = new com.intvaria.swing.RoundPanel();
        txtEmgName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        roundPanel10 = new com.intvaria.swing.RoundPanel();
        jTextField9 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        roundPanel22 = new com.intvaria.swing.RoundPanel();
        txtEmgRelationship = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        roundPanel14 = new com.intvaria.swing.RoundPanel();
        txtTelephone = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        roundPanel15 = new com.intvaria.swing.RoundPanel();
        txtEmgContact = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        opt1Y = new javax.swing.JRadioButton();
        opt1N = new javax.swing.JRadioButton();
        opt2Y = new javax.swing.JRadioButton();
        opt3Y = new javax.swing.JRadioButton();
        opt2N = new javax.swing.JRadioButton();
        opt3N = new javax.swing.JRadioButton();
        opt4N = new javax.swing.JRadioButton();
        opt4Y = new javax.swing.JRadioButton();
        opt5N = new javax.swing.JRadioButton();
        opt5Y = new javax.swing.JRadioButton();
        opt6N = new javax.swing.JRadioButton();
        opt6Y = new javax.swing.JRadioButton();
        opt7N = new javax.swing.JRadioButton();
        opt7Y = new javax.swing.JRadioButton();
        opt8N = new javax.swing.JRadioButton();
        opt8Y = new javax.swing.JRadioButton();
        opt9N = new javax.swing.JRadioButton();
        opt9Y = new javax.swing.JRadioButton();
        opt10N = new javax.swing.JRadioButton();
        opt10Y = new javax.swing.JRadioButton();
        opt11N = new javax.swing.JRadioButton();
        opt11Y = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        roundPanel6.setBackground(new java.awt.Color(25, 25, 25));

        jTextField5.setBackground(new java.awt.Color(25, 25, 25));
        jTextField5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(null);

        javax.swing.GroupLayout roundPanel6Layout = new javax.swing.GroupLayout(roundPanel6);
        roundPanel6.setLayout(roundPanel6Layout);
        roundPanel6Layout.setHorizontalGroup(
            roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5)
                .addContainerGap())
        );
        roundPanel6Layout.setVerticalGroup(
            roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(224, 224, 224));
        jLabel7.setText("First Name");

        setBackground(new java.awt.Color(25, 25, 25));

        jScrollPane2.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        roundPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("   Member Registrstion Form");

        proImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intvaria/image/profile.png"))); // NOI18N
        proImage.setOpaque(true);

        imageName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        imageName.setForeground(new java.awt.Color(153, 153, 153));
        imageName.setText("Image Name");

        imagePath2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        imagePath2.setForeground(new java.awt.Color(153, 153, 153));
        imagePath2.setText("Image Path");

        JFileChooser.setText("Choose");
        JFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFileChooserActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(224, 224, 224));
        jLabel18.setText("Membership Number");

        roundPanel21.setBackground(new java.awt.Color(25, 25, 25));

        txtMembershipNum.setBackground(new java.awt.Color(25, 25, 25));
        txtMembershipNum.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtMembershipNum.setForeground(new java.awt.Color(255, 255, 255));
        txtMembershipNum.setBorder(null);

        javax.swing.GroupLayout roundPanel21Layout = new javax.swing.GroupLayout(roundPanel21);
        roundPanel21.setLayout(roundPanel21Layout);
        roundPanel21Layout.setHorizontalGroup(
            roundPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMembershipNum, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanel21Layout.setVerticalGroup(
            roundPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMembershipNum, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jComboBox3.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Month", "3  Month", "6 Month", " ", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(224, 224, 224));
        jLabel19.setText("Membership Package");

        roundPanel5.setBackground(new java.awt.Color(25, 25, 25));

        txtBirthDay.setBackground(new java.awt.Color(25, 25, 25));
        txtBirthDay.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtBirthDay.setForeground(new java.awt.Color(255, 255, 255));
        txtBirthDay.setBorder(null);

        javax.swing.GroupLayout roundPanel5Layout = new javax.swing.GroupLayout(roundPanel5);
        roundPanel5.setLayout(roundPanel5Layout);
        roundPanel5Layout.setHorizontalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBirthDay, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel5Layout.setVerticalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBirthDay, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(224, 224, 224));
        jLabel6.setText("Birth Date");

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(224, 224, 224));
        jLabel17.setText("Last Name");

        roundPanel19.setBackground(new java.awt.Color(25, 25, 25));

        txtLastName.setBackground(new java.awt.Color(25, 25, 25));
        txtLastName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtLastName.setBorder(null);

        javax.swing.GroupLayout roundPanel19Layout = new javax.swing.GroupLayout(roundPanel19);
        roundPanel19.setLayout(roundPanel19Layout);
        roundPanel19Layout.setHorizontalGroup(
            roundPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel19Layout.setVerticalGroup(
            roundPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(224, 224, 224));
        jLabel9.setText("Telephone Number (Home)");

        roundPanel4.setBackground(new java.awt.Color(25, 25, 25));

        txtFirstName.setBackground(new java.awt.Color(25, 25, 25));
        txtFirstName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstName.setBorder(null);

        javax.swing.GroupLayout roundPanel4Layout = new javax.swing.GroupLayout(roundPanel4);
        roundPanel4.setLayout(roundPanel4Layout);
        roundPanel4Layout.setHorizontalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanel4Layout.setVerticalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(224, 224, 224));
        jLabel4.setText("First Name");

        jComboBox2.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(224, 224, 224));
        jLabel5.setText("Gender");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(224, 224, 224));
        jLabel8.setText("Mobile Number");

        roundPanel7.setBackground(new java.awt.Color(25, 25, 25));

        txtMobile.setBackground(new java.awt.Color(25, 25, 25));
        txtMobile.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtMobile.setForeground(new java.awt.Color(255, 255, 255));
        txtMobile.setBorder(null);

        javax.swing.GroupLayout roundPanel7Layout = new javax.swing.GroupLayout(roundPanel7);
        roundPanel7.setLayout(roundPanel7Layout);
        roundPanel7Layout.setHorizontalGroup(
            roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMobile)
                .addContainerGap())
        );
        roundPanel7Layout.setVerticalGroup(
            roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        roundPanel11.setBackground(new java.awt.Color(25, 25, 25));

        txtNic.setBackground(new java.awt.Color(25, 25, 25));
        txtNic.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtNic.setForeground(new java.awt.Color(255, 255, 255));
        txtNic.setBorder(null);

        javax.swing.GroupLayout roundPanel11Layout = new javax.swing.GroupLayout(roundPanel11);
        roundPanel11.setLayout(roundPanel11Layout);
        roundPanel11Layout.setHorizontalGroup(
            roundPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNic)
                .addContainerGap())
        );
        roundPanel11Layout.setVerticalGroup(
            roundPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNic, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(224, 224, 224));
        jLabel11.setText("NIC Number");

        roundPanel12.setBackground(new java.awt.Color(25, 25, 25));

        txtHomeAddress.setBackground(new java.awt.Color(25, 25, 25));
        txtHomeAddress.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtHomeAddress.setBorder(null);

        javax.swing.GroupLayout roundPanel12Layout = new javax.swing.GroupLayout(roundPanel12);
        roundPanel12.setLayout(roundPanel12Layout);
        roundPanel12Layout.setHorizontalGroup(
            roundPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHomeAddress)
                .addContainerGap())
        );
        roundPanel12Layout.setVerticalGroup(
            roundPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(224, 224, 224));
        jLabel13.setText("Home Address");

        roundPanel13.setBackground(new java.awt.Color(25, 25, 25));

        txtOfficeAddress.setBackground(new java.awt.Color(25, 25, 25));
        txtOfficeAddress.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtOfficeAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtOfficeAddress.setBorder(null);

        javax.swing.GroupLayout roundPanel13Layout = new javax.swing.GroupLayout(roundPanel13);
        roundPanel13.setLayout(roundPanel13Layout);
        roundPanel13Layout.setHorizontalGroup(
            roundPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOfficeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel13Layout.setVerticalGroup(
            roundPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtOfficeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(224, 224, 224));
        jLabel14.setText("Office Address");

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(224, 224, 224));
        jLabel20.setText("Emergency Contact Details");

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(224, 224, 224));
        jLabel10.setText("Name");

        roundPanel8.setBackground(new java.awt.Color(25, 25, 25));

        txtEmgName.setBackground(new java.awt.Color(25, 25, 25));
        txtEmgName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtEmgName.setForeground(new java.awt.Color(255, 255, 255));
        txtEmgName.setBorder(null);

        javax.swing.GroupLayout roundPanel8Layout = new javax.swing.GroupLayout(roundPanel8);
        roundPanel8.setLayout(roundPanel8Layout);
        roundPanel8Layout.setHorizontalGroup(
            roundPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmgName, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanel8Layout.setVerticalGroup(
            roundPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEmgName, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(224, 224, 224));
        jLabel12.setText("Telephone Number");

        roundPanel10.setBackground(new java.awt.Color(25, 25, 25));

        jTextField9.setBackground(new java.awt.Color(25, 25, 25));
        jTextField9.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setBorder(null);

        javax.swing.GroupLayout roundPanel10Layout = new javax.swing.GroupLayout(roundPanel10);
        roundPanel10.setLayout(roundPanel10Layout);
        roundPanel10Layout.setHorizontalGroup(
            roundPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanel10Layout.setVerticalGroup(
            roundPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(224, 224, 224));
        jLabel21.setText("Relationship");

        roundPanel22.setBackground(new java.awt.Color(25, 25, 25));

        txtEmgRelationship.setBackground(new java.awt.Color(25, 25, 25));
        txtEmgRelationship.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtEmgRelationship.setForeground(new java.awt.Color(255, 255, 255));
        txtEmgRelationship.setBorder(null);

        javax.swing.GroupLayout roundPanel22Layout = new javax.swing.GroupLayout(roundPanel22);
        roundPanel22.setLayout(roundPanel22Layout);
        roundPanel22Layout.setHorizontalGroup(
            roundPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmgRelationship)
                .addContainerGap())
        );
        roundPanel22Layout.setVerticalGroup(
            roundPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEmgRelationship, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(224, 224, 224));
        jLabel15.setText("Health Information");

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(224, 224, 224));
        jLabel16.setText("Are You a Heart Patient?");

        jLabel22.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(224, 224, 224));
        jLabel22.setText("Have You had a Heart Attack Before?");

        jLabel23.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(224, 224, 224));
        jLabel23.setText("Do you feel pain when exercising?");

        jLabel24.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(224, 224, 224));
        jLabel24.setText("Do you suffer from high blood pressure, high choleterol or diabetes?");

        jLabel25.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(224, 224, 224));
        jLabel25.setText("Do you suffer from asthma?");

        jLabel26.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(224, 224, 224));
        jLabel26.setText("Do you have any bone or muscle aches?");

        jLabel27.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(224, 224, 224));
        jLabel27.setText("Are you receiving treatment for any medical condition?");

        jLabel28.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(224, 224, 224));
        jLabel28.setText("Have you ever felt asthma / dizziness / shortness of breath lose while you exercising?");

        jLabel29.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(224, 224, 224));
        jLabel29.setText("Do you suffer from asthma?");

        jLabel30.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(224, 224, 224));
        jLabel30.setText("Have you had surgery?");

        jLabel31.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(224, 224, 224));
        jLabel31.setText("Has you doctor advices you not to Exercise");

        roundPanel14.setBackground(new java.awt.Color(25, 25, 25));

        txtTelephone.setBackground(new java.awt.Color(25, 25, 25));
        txtTelephone.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTelephone.setForeground(new java.awt.Color(255, 255, 255));
        txtTelephone.setBorder(null);

        jLabel32.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(224, 224, 224));
        jLabel32.setText("Mobile Number");

        javax.swing.GroupLayout roundPanel14Layout = new javax.swing.GroupLayout(roundPanel14);
        roundPanel14.setLayout(roundPanel14Layout);
        roundPanel14Layout.setHorizontalGroup(
            roundPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTelephone)
                .addContainerGap())
        );
        roundPanel14Layout.setVerticalGroup(
            roundPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel33.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(224, 224, 224));
        jLabel33.setText("Home Telephone ");

        jLabel34.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(224, 224, 224));
        jLabel34.setText("Contact Number");

        roundPanel15.setBackground(new java.awt.Color(25, 25, 25));

        txtEmgContact.setBackground(new java.awt.Color(25, 25, 25));
        txtEmgContact.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtEmgContact.setForeground(new java.awt.Color(255, 255, 255));
        txtEmgContact.setBorder(null);

        jLabel35.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(224, 224, 224));
        jLabel35.setText("Mobile Number");

        javax.swing.GroupLayout roundPanel15Layout = new javax.swing.GroupLayout(roundPanel15);
        roundPanel15.setLayout(roundPanel15Layout);
        roundPanel15Layout.setHorizontalGroup(
            roundPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmgContact, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanel15Layout.setVerticalGroup(
            roundPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEmgContact, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        opt1Y.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(opt1Y);
        opt1Y.setForeground(new java.awt.Color(204, 204, 204));
        opt1Y.setText("Yes");
        opt1Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1YActionPerformed(evt);
            }
        });

        opt1N.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(opt1N);
        opt1N.setForeground(new java.awt.Color(204, 204, 204));
        opt1N.setSelected(true);
        opt1N.setText("No");

        opt2Y.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(opt2Y);
        opt2Y.setForeground(new java.awt.Color(255, 255, 255));
        opt2Y.setText("Yes");

        opt3Y.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup3.add(opt3Y);
        opt3Y.setForeground(new java.awt.Color(255, 255, 255));
        opt3Y.setText("Yes");

        opt2N.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(opt2N);
        opt2N.setForeground(new java.awt.Color(255, 255, 255));
        opt2N.setSelected(true);
        opt2N.setText("No");

        opt3N.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup3.add(opt3N);
        opt3N.setForeground(new java.awt.Color(255, 255, 255));
        opt3N.setSelected(true);
        opt3N.setText("No");
        opt3N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3NActionPerformed(evt);
            }
        });

        opt4N.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup4.add(opt4N);
        opt4N.setForeground(new java.awt.Color(255, 255, 255));
        opt4N.setSelected(true);
        opt4N.setText("No");
        opt4N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4NActionPerformed(evt);
            }
        });

        opt4Y.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup4.add(opt4Y);
        opt4Y.setForeground(new java.awt.Color(255, 255, 255));
        opt4Y.setText("Yes");

        opt5N.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup5.add(opt5N);
        opt5N.setForeground(new java.awt.Color(255, 255, 255));
        opt5N.setSelected(true);
        opt5N.setText("No");
        opt5N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt5NActionPerformed(evt);
            }
        });

        opt5Y.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup5.add(opt5Y);
        opt5Y.setForeground(new java.awt.Color(255, 255, 255));
        opt5Y.setText("Yes");

        opt6N.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup6.add(opt6N);
        opt6N.setForeground(new java.awt.Color(255, 255, 255));
        opt6N.setSelected(true);
        opt6N.setText("No");
        opt6N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt6NActionPerformed(evt);
            }
        });

        opt6Y.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup6.add(opt6Y);
        opt6Y.setForeground(new java.awt.Color(255, 255, 255));
        opt6Y.setText("Yes");

        opt7N.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup7.add(opt7N);
        opt7N.setForeground(new java.awt.Color(255, 255, 255));
        opt7N.setSelected(true);
        opt7N.setText("No");
        opt7N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt7NActionPerformed(evt);
            }
        });

        opt7Y.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup7.add(opt7Y);
        opt7Y.setForeground(new java.awt.Color(255, 255, 255));
        opt7Y.setText("Yes");

        opt8N.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup8.add(opt8N);
        opt8N.setForeground(new java.awt.Color(255, 255, 255));
        opt8N.setSelected(true);
        opt8N.setText("No");
        opt8N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt8NActionPerformed(evt);
            }
        });

        opt8Y.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup8.add(opt8Y);
        opt8Y.setForeground(new java.awt.Color(255, 255, 255));
        opt8Y.setText("Yes");

        opt9N.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup9.add(opt9N);
        opt9N.setForeground(new java.awt.Color(255, 255, 255));
        opt9N.setSelected(true);
        opt9N.setText("No");
        opt9N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt9NActionPerformed(evt);
            }
        });

        opt9Y.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup9.add(opt9Y);
        opt9Y.setForeground(new java.awt.Color(255, 255, 255));
        opt9Y.setText("Yes");
        opt9Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt9YActionPerformed(evt);
            }
        });

        opt10N.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup10.add(opt10N);
        opt10N.setForeground(new java.awt.Color(255, 255, 255));
        opt10N.setSelected(true);
        opt10N.setText("No");
        opt10N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt10NActionPerformed(evt);
            }
        });

        opt10Y.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup10.add(opt10Y);
        opt10Y.setForeground(new java.awt.Color(255, 255, 255));
        opt10Y.setText("Yes");
        opt10Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt10YActionPerformed(evt);
            }
        });

        opt11N.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup11.add(opt11N);
        opt11N.setForeground(new java.awt.Color(255, 255, 255));
        opt11N.setSelected(true);
        opt11N.setText("No");
        opt11N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt11NActionPerformed(evt);
            }
        });

        opt11Y.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup11.add(opt11Y);
        opt11Y.setForeground(new java.awt.Color(255, 255, 255));
        opt11Y.setText("Yes");

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Subbmit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel34)
                                .addComponent(roundPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(roundPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(roundPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roundPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roundPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(95, 95, 95)
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel17)
                                    .addComponent(roundPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(roundPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1061, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(406, 406, 406))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(roundPanel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel10)
                                .addGap(194, 194, 194))
                            .addComponent(roundPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(roundPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(377, 377, 377))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)
                                    .addGroup(roundPanel1Layout.createSequentialGroup()
                                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel28))
                                        .addGap(30, 30, 30)
                                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(opt2Y)
                                            .addComponent(opt3Y)
                                            .addComponent(opt1Y, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(opt4Y)
                                            .addComponent(opt5Y)
                                            .addComponent(opt6Y)
                                            .addComponent(opt7Y)
                                            .addComponent(opt8Y)
                                            .addComponent(opt9Y)
                                            .addComponent(opt10Y)
                                            .addComponent(opt11Y))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(opt11N)
                                            .addComponent(opt10N)
                                            .addComponent(opt9N)
                                            .addComponent(opt8N)
                                            .addComponent(opt7N)
                                            .addComponent(opt6N)
                                            .addComponent(opt5N)
                                            .addComponent(opt4N)
                                            .addComponent(opt1N, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(opt3N)
                                            .addComponent(opt2N)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                                        .addGap(440, 440, 440)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(roundPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addComponent(roundPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(proImage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagePath2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addComponent(roundPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, 1325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(568, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proImage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(imageName)
                        .addGap(15, 15, 15)
                        .addComponent(imagePath2)
                        .addGap(16, 16, 16)
                        .addComponent(JFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(roundPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)))
                .addGap(18, 18, 18)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(roundPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(roundPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(roundPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(roundPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(roundPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(roundPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(roundPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roundPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)
                        .addComponent(roundPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addGap(8, 8, 8)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(opt1Y, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(opt1N, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22))
                            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(opt2Y)
                                .addComponent(opt2N)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23))
                    .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(opt3Y)
                        .addComponent(opt3N)))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(opt4Y)
                    .addComponent(opt4N))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(opt5Y)
                    .addComponent(opt5N))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(opt6Y)
                    .addComponent(opt6N))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(opt7Y)
                    .addComponent(opt7N))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(opt8Y)
                    .addComponent(opt8N))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(opt9Y)
                    .addComponent(opt9N))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(opt10Y)
                    .addComponent(opt10N))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(opt11Y)
                    .addComponent(opt11N))
                .addGap(45, 45, 45)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(371, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(roundPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1910, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void JFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFileChooserActionPerformed
         JFileChooser file=new JFileChooser();
        file.showOpenDialog(file);
        file.setCurrentDirectory(new File("user.dir"));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("All Pic", "ong","jpg","jpeg","gif");
        file.showSaveDialog(null);

        int a =file.showSaveDialog(null);
       
             f =file.getSelectedFile();
            String p= f.getAbsolutePath();
            imagePath2.setText(p);
            imageName.setText(f.getName());
            proImage.setIcon(setIcon(p, null));
        
    }//GEN-LAST:event_JFileChooserActionPerformed

    private void opt1YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1YActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt1YActionPerformed

    private void opt3NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt3NActionPerformed

    private void opt4NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt4NActionPerformed

    private void opt5NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt5NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt5NActionPerformed

    private void opt6NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt6NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt6NActionPerformed

    private void opt7NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt7NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt7NActionPerformed

    private void opt8NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt8NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt8NActionPerformed

    private void opt9NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt9NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt9NActionPerformed

    private void opt10NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt10NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt10NActionPerformed

    private void opt11NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt11NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt11NActionPerformed

    private void opt9YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt9YActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt9YActionPerformed

    private void opt10YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt10YActionPerformed
       
 
    }//GEN-LAST:event_opt10YActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
               String membershipNumber=txtMembershipNum.getText();
        String firstName=txtFirstName.getText();
        String lastName=txtLastName.getText();
        String birthday=txtBirthDay.getText();
        String gender=jComboBox2.getSelectedItem().toString();
        String nic=txtNic.getText();
        String homeTel=txtTelephone.getText();
        String mobile=txtMobile.getText();
        String homeAddress=txtHomeAddress.getText();
        String officeAdderss=txtOfficeAddress.getText();
        String emgName=txtEmgName.getText();
        String emgContact=txtEmgContact.getText();
        String emgRelation=txtEmgRelationship.getText();
        Options options;
        String packageName=jComboBox3.getSelectedItem().toString();
        
        Member member=new Member();
        
        if(membershipNumber.length()!=0){
            if(memberDao.getSingleMember(Long.parseLong(membershipNumber)).getId()==null){
          
            member.setMembership_number(Long.parseLong(membershipNumber));
            member.setFirst_name(firstName);
            member.setLast_name(lastName);
            member.setBirthday(birthday);
            member.setGender(gender);
            member.setHome_telephone(homeTel);
            member.setMobile(mobile);
            member.setHome_address(homeAddress);
            member.setOffice_address(officeAdderss);
            member.setEmerg_name(emgName);
            member.setEmerg_contact(emgContact);
            member.setEmerg_relation(emgRelation);
            member.setNic(nic);
            
            try {
                  member.setProImage(converImage(f));
            } catch (Exception e) {
            }
          
            options=setOptionValuse(Long.parseLong(membershipNumber));
           boolean isSuccess=memberDao.saveMember(member,options,packageName);
           
           if(isSuccess==true){
                JOptionPane.showMessageDialog(null, "Member Saved");
                 reset();
           }else{
                JOptionPane.showMessageDialog(null, "Member not saved . Try again !","Werning",JOptionPane.WARNING_MESSAGE);
           }
        }else{
                JOptionPane.showMessageDialog(null, "Membership Number Alrady Used ","Werning",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please Enter Membership Number");
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private Options setOptionValuse(Long memberId){
        Options options=new Options();
        options.setOpt1(buttonGroup1.getSelection().getActionCommand());
        options.setOpt2(buttonGroup2.getSelection().getActionCommand());
        options.setOpt3(buttonGroup3.getSelection().getActionCommand());
        options.setOpt4(buttonGroup4.getSelection().getActionCommand());
        options.setOpt5(buttonGroup5.getSelection().getActionCommand());
        options.setOpt6(buttonGroup6.getSelection().getActionCommand());
        options.setOpt7(buttonGroup7.getSelection().getActionCommand());
        options.setOpt8(buttonGroup8.getSelection().getActionCommand());
        options.setOpt9(buttonGroup9.getSelection().getActionCommand());
        options.setOpt10(buttonGroup10.getSelection().getActionCommand());
        options.setOpt11(buttonGroup11.getSelection().getActionCommand());
        options.setMember_Id(memberId);
        
        
        return options;
      
        
    }
    
    private byte[] converImage(File file) throws IOException{
         BufferedImage bImage ;
          String filePath = "src\\com\\intvaria\\image\\profile.png";
         if(file==null){
             bImage = ImageIO.read(new File(filePath));
         }else{
             bImage = ImageIO.read(file);
         }
      ByteArrayOutputStream bos = new ByteArrayOutputStream();
      ImageIO.write(bImage, "jpg", bos );
      byte [] data = bos.toByteArray();
      
      return data;
    } 
    
    
    
    private void reset(){
        txtMembershipNum.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtBirthDay.setText("");
        txtNic.setText("");
        txtMobile.setText("");
        txtTelephone.setText("");
        txtHomeAddress.setText("");
        txtOfficeAddress.setText("");
        txtEmgContact.setText("");
        txtEmgName.setText("");
        txtEmgRelationship.setText("");
        opt1N.setSelected(true);
        opt2N.setSelected(true);
        opt3N.setSelected(true);
        opt4N.setSelected(true);
        opt5N.setSelected(true);
        opt6N.setSelected(true);
        opt7N.setSelected(true);
        opt8N.setSelected(true);
        opt9N.setSelected(true);
        opt10N.setSelected(true);
        opt11N.setSelected(true);
        jComboBox3.setSelectedIndex(0);
         jComboBox2.setSelectedIndex(0);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JFileChooser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private com.intvaria.component.Header header2;
    private javax.swing.JLabel imageName;
    private javax.swing.JLabel imagePath2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JRadioButton opt10N;
    private javax.swing.JRadioButton opt10Y;
    private javax.swing.JRadioButton opt11N;
    private javax.swing.JRadioButton opt11Y;
    private javax.swing.JRadioButton opt1N;
    private javax.swing.JRadioButton opt1Y;
    private javax.swing.JRadioButton opt2N;
    private javax.swing.JRadioButton opt2Y;
    private javax.swing.JRadioButton opt3N;
    private javax.swing.JRadioButton opt3Y;
    private javax.swing.JRadioButton opt4N;
    private javax.swing.JRadioButton opt4Y;
    private javax.swing.JRadioButton opt5N;
    private javax.swing.JRadioButton opt5Y;
    private javax.swing.JRadioButton opt6N;
    private javax.swing.JRadioButton opt6Y;
    private javax.swing.JRadioButton opt7N;
    private javax.swing.JRadioButton opt7Y;
    private javax.swing.JRadioButton opt8N;
    private javax.swing.JRadioButton opt8Y;
    private javax.swing.JRadioButton opt9N;
    private javax.swing.JRadioButton opt9Y;
    private com.intvaria.swing.ImageAvatar proImage;
    private com.intvaria.swing.RoundPanel roundPanel1;
    private com.intvaria.swing.RoundPanel roundPanel10;
    private com.intvaria.swing.RoundPanel roundPanel11;
    private com.intvaria.swing.RoundPanel roundPanel12;
    private com.intvaria.swing.RoundPanel roundPanel13;
    private com.intvaria.swing.RoundPanel roundPanel14;
    private com.intvaria.swing.RoundPanel roundPanel15;
    private com.intvaria.swing.RoundPanel roundPanel19;
    private com.intvaria.swing.RoundPanel roundPanel21;
    private com.intvaria.swing.RoundPanel roundPanel22;
    private com.intvaria.swing.RoundPanel roundPanel4;
    private com.intvaria.swing.RoundPanel roundPanel5;
    private com.intvaria.swing.RoundPanel roundPanel6;
    private com.intvaria.swing.RoundPanel roundPanel7;
    private com.intvaria.swing.RoundPanel roundPanel8;
    private javax.swing.JTextField txtBirthDay;
    private javax.swing.JTextField txtEmgContact;
    private javax.swing.JTextField txtEmgName;
    private javax.swing.JTextField txtEmgRelationship;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHomeAddress;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMembershipNum;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtOfficeAddress;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables

  
}
