/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.intvaria.form;

import com.intvaria.DAO.StockDAO;
import com.intvaria.DAO.UserDAO;
import com.intvaria.entity.Category;
import com.intvaria.entity.Item;
import com.intvaria.entity.User;
import com.intvaria.main.AddItem;
import com.intvaria.main.Categories;
import com.intvaria.main.Edititem;
import com.intvaria.main.Singleitem;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.ActionMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Dhanushka
 */
public class viewallitem extends javax.swing.JPanel {

   
    byte[] image;
    String imagePath="";
    ImageIcon myImage;
    UserDAO userDao=new UserDAO();
    int stockUserIndex=0;
    StockDAO stockDao=new StockDAO();
    int index;
    int cell;
    TableModel tbm;
    String cellValue;
    public viewallitem() {
        initComponents();
        getAllItems();
      setUser();
      stockUserIndex=combUser.getSelectedIndex();

    }
    
      
    
    public void getAllItems(){
        
         ArrayList<Item> itemList;
         
         if(userDao.getLoggedUserDetails().getUserType().equals("admin")){
               itemList=(ArrayList<Item>) stockDao.getAllItems();
         }else{
             itemList= (ArrayList<Item>) stockDao.searchItems(0, "",0);
         }
          
    
        String itemId,category,name,price,stock;
        if(itemList.size()>0){
            for(int i=0;i < itemList.size();i++){
                category=itemList.get(i).getCategory();
                name=itemList.get(i).getName();
                itemId=String.valueOf(itemList.get(i).getId());
                price=String.valueOf(itemList.get(i).getPrice());
                stock=String.valueOf(itemList.get(i).getStock());
                String toData[]={itemId,category,name,price,stock};
                DefaultTableModel tbMdel=(DefaultTableModel) jTable1.getModel();
                tbMdel.addRow(toData);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel6 = new com.intvaria.swing.RoundPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        roundPanel1 = new com.intvaria.swing.RoundPanel();
        combUser = new javax.swing.JComboBox<String>();
        roundPanel21 = new com.intvaria.swing.RoundPanel();
        txtKeyword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        combType = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        roundPanel6.setBackground(new java.awt.Color(25, 25, 25));

        jTextField5.setBackground(new java.awt.Color(25, 25, 25));
        jTextField5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(null);

        javax.swing.GroupLayout roundPanel6Layout = new javax.swing.GroupLayout(roundPanel6);
        roundPanel6.setLayout(roundPanel6Layout);
        roundPanel6Layout.setHorizontalGroup(
            roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5)
                .addContainerGap())
        );
        roundPanel6Layout.setVerticalGroup(
            roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(224, 224, 224));
        jLabel7.setText("First Name");

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setText("Make A Sale");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2.setText("Edit Item");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setBackground(new java.awt.Color(25, 25, 25));

        roundPanel1.setBackground(new java.awt.Color(51, 51, 51));

        combUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combUserActionPerformed(evt);
            }
        });
        combUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combUserKeyPressed(evt);
            }
        });

        roundPanel21.setBackground(new java.awt.Color(204, 204, 204));

        txtKeyword.setBackground(new java.awt.Color(204, 204, 204));
        txtKeyword.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        txtKeyword.setBorder(null);
        txtKeyword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtKeywordMouseReleased(evt);
            }
        });
        txtKeyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeywordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel21Layout = new javax.swing.GroupLayout(roundPanel21);
        roundPanel21.setLayout(roundPanel21Layout);
        roundPanel21Layout.setHorizontalGroup(
            roundPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtKeyword)
                .addContainerGap())
        );
        roundPanel21Layout.setVerticalGroup(
            roundPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtKeyword, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("All Item");

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Category", "Item name", "Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTable1InputMethodTextChanged(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Add Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Category");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        combType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Item Name", "Category" }));
        combType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combTypeActionPerformed(evt);
            }
        });
        combType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combTypeKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select User");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Serch Type");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Keyword here");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(combUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combUser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combType, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combUserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // add item
       if("admin".equals(userDao.getLoggedUserDetails().getUserType())){
            JFrame addItem=new AddItem();
       addItem.setVisible(true);
       }else{
           JOptionPane.showMessageDialog(null,"You have not permission to add new item");
       }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       // category
       User user=userDao.getLoggedUserDetails();
       if(user.getUserType().equals("admin")){
           JFrame category=new Categories();
           category.setVisible(true);
       }else{
           JOptionPane.showMessageDialog(null,"You have not permission to add, edit, delete category");
       }
        
    }//GEN-LAST:event_jButton3ActionPerformed

     public void setUser(){
              Vector comboBoxItems=new Vector();
        List<User> userList=userDao.getAllUsers();
        User user=userDao.getLoggedUserDetails();
         if(!user.getUserType().equals("coach")){
         
        
        if(userList.size()>0){
            comboBoxItems.add("Admin");
          //  comboBoxItems.add("Select Package");
            for(int i=0 ; i< userList.size() ; i++){
                if(!userList.get(i).getUserType().equals("admin")){
                   
                    comboBoxItems.add(userList.get(i).getFirstName() + " " +userList.get(i).getLastName() );
                }
               
            }
            
        }
         }else{
             comboBoxItems.add(user.getFirstName()+" "+user.getLastName());
         }
    
         final DefaultComboBoxModel model = new DefaultComboBoxModel(comboBoxItems);
             combUser.setModel(model);
        }
    
    public void searchItems(){
        int type=combType.getSelectedIndex();
        
        String keyword=txtKeyword.getText();
        int user=combUser.getSelectedIndex();
        DefaultTableModel dm = (DefaultTableModel)jTable1.getModel();
     dm.getDataVector().removeAllElements();
       dm.fireTableDataChanged();
      
             ArrayList<Item> itemList=(ArrayList<Item>) stockDao.searchItems(type, keyword,user);
         String itemId,category,name,price,stock;
        if(itemList.size()>0){
            for(int i=0;i < itemList.size();i++){
                category=itemList.get(i).getCategory();
                name=itemList.get(i).getName();
                itemId=String.valueOf(itemList.get(i).getId());
                price=String.valueOf(itemList.get(i).getPrice());
                stock=String.valueOf(itemList.get(i).getStock());
                String toData[]={itemId,category,name,price,stock};
                DefaultTableModel tbMdel=(DefaultTableModel) jTable1.getModel();
                tbMdel.addRow(toData);
            }
        }
        stockUserIndex=combUser.getSelectedIndex();
        
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // search 
        searchItems();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtKeywordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKeywordMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeywordMouseReleased

    private void txtKeywordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeywordKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchItems();
        
        }
    }//GEN-LAST:event_txtKeywordKeyPressed

    private void combUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combUserKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchItems();
        
        }
    }//GEN-LAST:event_combUserKeyPressed

    private void combTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combTypeActionPerformed

    private void combTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combTypeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_combTypeKeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // update qty
        
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           InputMap im = jTable1.getInputMap(JTable.WHEN_FOCUSED);
         ActionMap am = jTable1.getActionMap();
       }
           
           
      

        
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1InputMethodTextChanged
       
    }//GEN-LAST:event_jTable1InputMethodTextChanged

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
      if ("tableCellEditor".equals(evt.getPropertyName()))
        { 
            
           
            
             tbm=jTable1.getModel();
             String itemId=(String) tbm.getValueAt(index, 0);
            String stock=(String) tbm.getValueAt(index, cell);
            if (!jTable1.isEditing()){
              int resullt=  JOptionPane.showConfirmDialog(null, "Do you want to save stock");
               
             if(resullt==JOptionPane.YES_OPTION){
                 
                  if("admin".equals(userDao.getLoggedUserDetails().getUserType())){
                  if(  stockUserIndex!=0){
                      boolean isSaved=stockDao.updateStock(Integer.parseInt(itemId), stockUserIndex, Integer.parseInt(stock)-Integer.parseInt(cellValue));
                if(isSaved==true){
                    JOptionPane.showMessageDialog(null, "Stock updated");
                }else{
                    JOptionPane.showMessageDialog(null, "Stock not updated. Try agin!" ,"warning" , JOptionPane.WARNING_MESSAGE);
                }
                 }else{
                     if(userDao.getLoggedUserDetails().getUserType().equals("coach") ){
                           boolean isSaved=stockDao.updateStock(Integer.parseInt(itemId), stockUserIndex, Integer.parseInt(stock)-Integer.parseInt(cellValue));
                if(isSaved==true){
                    JOptionPane.showMessageDialog(null, "Stock updated");
                }else{
                    JOptionPane.showMessageDialog(null, "Stock not updated. Try agin!" ,"warning" , JOptionPane.WARNING_MESSAGE);
                }
                     }else{
                        JOptionPane.showMessageDialog(null, "Main stock can't be change directly . please flter stock according to a coch first !" ,"warning" , JOptionPane.WARNING_MESSAGE);
                     tbm.setValueAt(cellValue, index, cell); 
                     }
                     
                 }
               
       }else{
                       tbm.setValueAt(cellValue, index, cell);
           JOptionPane.showMessageDialog(null,"You have not permission to change stock directly");
       }
                 
         
             }else{
                 
                 tbm.setValueAt(cellValue, index, cell);
             
            }
                
            
                // code for editing stopped;
        }
        }
    }//GEN-LAST:event_jTable1PropertyChange

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         index=   jTable1.getSelectedRow();
                 cell=jTable1.getSelectedColumn();
              tbm=jTable1.getModel();
              cellValue=(String) tbm.getValueAt(index, cell);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //make a sale
         int index = jTable1.getSelectedRow();
        TableModel tbm = jTable1.getModel();
        String itemId = (String) tbm.getValueAt(index, 0);
        User user=userDao.getLoggedUserDetails();
        
        if(user.getUserType().equals("admin")){
            if(stockUserIndex==0){
                 JOptionPane.showMessageDialog(null, "You can't make a sale as admin.Please filter items according to a coach first." , "Warning",JOptionPane.WARNING_MESSAGE);
            }else{
                List<User> userList=userDao.getAllUsersByType("coach");
                User selectedUser=userList.get(stockUserIndex-1);
                  JFrame item=new Singleitem(Integer.parseInt(itemId),selectedUser.getUserId());
                  item.setVisible(true); 
            }
           
        }else{
            
            JFrame item=new Singleitem(Integer.parseInt(itemId),user.getUserId());
             item.setVisible(true); 
        }
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
       if(evt.isPopupTrigger()){
          JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            
             if (! source.isRowSelected(row))
                source.changeSelection(row, column, false, false);
            
         jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
      }
    }//GEN-LAST:event_jTable1MouseReleased

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //edit
         int index = jTable1.getSelectedRow();
        TableModel tbm = jTable1.getModel();
        String itemId = (String) tbm.getValueAt(index, 0);
        if(userDao.getLoggedUserDetails().getUserType().equals("admin") ){
           JFrame edit=new Edititem(Integer.parseInt(itemId));
        edit.setVisible(true); 
            
        }else{
          JOptionPane.showMessageDialog(null, "You have not permissions to edit item details !" , "Warning",JOptionPane.WARNING_MESSAGE);  
        }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JComboBox<String> combType;
    private javax.swing.JComboBox<String> combUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private com.intvaria.swing.RoundPanel roundPanel1;
    private com.intvaria.swing.RoundPanel roundPanel21;
    private com.intvaria.swing.RoundPanel roundPanel6;
    private javax.swing.JTextField txtKeyword;
    // End of variables declaration//GEN-END:variables

  
}
